fail_fast: false # allows all checks to run even if one fails
repos:
  # Common checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  # Rust-specific checks
  - repo: local
    hooks:
      - id: cargo-fmt # Code formatting
        name: cargo fmt
        description: format files with rustfmt
        entry: bash -c 'cargo fmt -- --check'
        language: rust
        files: \.rs$
        args: [ ]
      - id: cargo-deny # Dependency checking
        name: cargo deny check
        description: check cargo dependencies
        entry: bash -c 'cargo deny check -d'
        language: rust
        files: \.rs$
        args: [ ]
      - id: typos # Typo checking
        name: typos
        description: check typo
        entry: bash -c 'typos -c _typos.toml'
        language: rust
        files: \.*$
        pass_filenames: false
      - id: cargo-check # Package error checking
        name: cargo check
        description: check the package for errors
        entry: bash -c 'cargo check --all'
        language: rust
        files: \.rs$
        pass_filenames: false
      - id: cargo-clippy # Linting
        name: cargo clippy
        description: lint rust sources
        entry: bash -c 'cargo clippy --all-targets --all-features --tests --benches -- -D warnings'
        language: rust
        files: \.rs$
        pass_filenames: false
      - id: cargo-test # Unit testing
        name: cargo test
        description: unit test for the project
        entry: bash -c 'cargo nextest run --all-features'
        language: rust
        files: \.rs$
        pass_filenames: false
